### ISSUE TITLE
[BUG] : Toast appears after saving a page with no changes

### ISSUE THREAD

**Issue by filippo-fonseca** [Dev-CasperTheGhost/notey.app#124]
**Bug Description**
A success toast pops up after saving a page, even though nothing has changed.

**To Reproduce**
1. Go to a note
2. Click on edit
3. Save without changing anything
4. See toast pop up

**Expected behavior**
If nothing is changed, it shouldn't show the modal or any time of feedback, as there is nothing to update. :)

**Comment by Dev-CasperTheGhost** [comment]
I'm currently rewriting the app with next.js, it'll be fixed once finished :)

**Comment by filippo-fonseca** [comment]
Cool! Just thought I'd point it out. :)
